integer_type=12
float_type=12.43
list_type=[1,2,4,5]
bool_type=False
string_type="Hello"
print(type(integer_type))
print(type(float_type))
print(type(bool_type))
print(type(string_type))
print(type(list_type))
